-- MySQL Script generated by MySQL Workbench
-- Tue Apr 25 16:29:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sistema` DEFAULT CHARACTER SET latin1 ;
USE `db_sistema` ;

-- -----------------------------------------------------
-- Table `db_sistema`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`perfil` (
  `idperfil` INT(11) NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_sistema`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `perfil_idperfil` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_perfil_idx` (`perfil_idperfil` ASC),
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `db_sistema`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_sistema`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`aluno` (
  `idaluno` INT(11) NOT NULL AUTO_INCREMENT,
  `matricula` INT(11) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `turma` VARCHAR(20) NOT NULL,
  `turno` VARCHAR(20) NOT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idaluno`),
  INDEX `fk_aluno_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_aluno_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db_sistema`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_sistema`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `rg` INT(11) NULL DEFAULT NULL,
  `datanascimento` DATE NULL DEFAULT NULL,
  `endereco` VARCHAR(150) NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db_sistema`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_sistema`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`funcionario` (
  `idfuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `matricula` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `dataadmissao` DATE NULL DEFAULT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  INDEX `fk_funcionario_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db_sistema`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
