-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 11:12:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema popworld
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `popworld` ;

-- -----------------------------------------------------
-- Schema popworld
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `popworld` DEFAULT CHARACTER SET utf8 ;
USE `popworld` ;

-- -----------------------------------------------------
-- Table `popworld`.`assinatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popworld`.`assinatura` ;

CREATE TABLE IF NOT EXISTS `popworld`.`assinatura` (
  `idassinatura` INT NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `periodo` INT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`idassinatura`))
ENGINE = InnoDB;

INSERT INTO assinatura (valor,descricao, periodo, `data`) values
('1.00',  'MENSAL', '30', '2023-11-20'),
       ('3.00','SEMESTRAL', '180', '2023-11-20'),
	   ('6.00','ANUAL', '365', '2023-11-20');

-- -----------------------------------------------------
-- Table `popworld`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popworld`.`produto` ;

CREATE TABLE IF NOT EXISTS `popworld`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `valor` DECIMAL(13,2) NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;
INSERT INTO produto (nome, valor, codigo) values 
('albúm Olivia Rodrigo', '30.00', '306'),
('albúm Dua Lipa ', '50.00', '354');




-- -----------------------------------------------------
-- Table `popworld`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popworld`.`perfil` ;

CREATE TABLE IF NOT EXISTS `popworld`.`perfil` (
  `idperfil` INT NOT NULL  AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;
INSERT INTO perfil (nome) values
('Administrador'),
('Artista'),
('Usuário');


-- -----------------------------------------------------
-- Table `popworld`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popworld`.`usuario` ;

CREATE TABLE IF NOT EXISTS `popworld`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(50) NULL,
  `ddi` VARCHAR(2) NULL,
  `ddd` VARCHAR(2) NULL,
  `numero` VARCHAR(7) NULL,
  `cpf` VARCHAR(11) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `discografia` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_perfil_idx` (`perfil_idperfil` ASC) ,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `popworld`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO usuario (nome,email,senha,perfil_idperfil) values
('administrador', 'adm@gmail.com', MD5('123'), '1');



-- -----------------------------------------------------
-- Table `popworld`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popworld`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `popworld`.`carrinho` (
  `idcarrinho` INT NOT NULL AUTO_INCREMENT,
  `itens` VARCHAR(45) NULL,
  `quantidade` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  `loja_idcarrinho` INT NOT NULL,
  `datapagamento` DATE NULL,
  `tipopagamento` VARCHAR(45) NULL COMMENT 'PIX\nCartão Débito\nCartão Crédito',
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  INDEX `fk_carrinho_usuario1_idx` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_carrinho_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `popworld`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popworld`.`conteudo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popworld`.`conteudo` ;

CREATE TABLE IF NOT EXISTS `popworld`.`conteudo` (
  `idconteudo` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(245) NULL,
  `imagem` VARCHAR(45) NULL,
  `dataFinal` DATE NULL COMMENT 'Data de validade final da assinatura',
  `nomeplaylists` VARCHAR(145) NULL COMMENT 'nome do arquivo da música',
  `datapagamento` DATE NULL COMMENT 'Data de pagameto da assinatura',
  `valorassinatura` DECIMAL(13,2) NULL DEFAULT 0,
  `tipopagamento` VARCHAR(45) NULL COMMENT 'PIX\nCartão Débito\nCartão Crédito',
  `assinatura_idassinatura` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idconteudo`),
  INDEX `fk_conteudo_assinatura1_idx` (`assinatura_idassinatura` ASC) ,
  INDEX `fk_conteudo_usuario1_idx` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_conteudo_assinatura1`
    FOREIGN KEY (`assinatura_idassinatura`)
    REFERENCES `popworld`.`assinatura` (`idassinatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conteudo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `popworld`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popworld`.`carrinho_itens_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popworld`.`carrinho_itens_produto` ;

CREATE TABLE IF NOT EXISTS `popworld`.`carrinho_itens_produto` (
  `carrinho_idcarrinho` INT NOT NULL  AUTO_INCREMENT,
  `produto_idproduto` INT NOT NULL,
  `valor` DECIMAL(13,2) NULL DEFAULT 0,
  PRIMARY KEY (`carrinho_idcarrinho`, `produto_idproduto`),
  INDEX `fk_carrinho_has_produto_produto1_idx` (`produto_idproduto` ASC) ,
  INDEX `fk_carrinho_has_produto_carrinho1_idx` (`carrinho_idcarrinho` ASC) ,
  CONSTRAINT `fk_carrinho_has_produto_carrinho1`
    FOREIGN KEY (`carrinho_idcarrinho`)
    REFERENCES `popworld`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinho_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `popworld`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
